test_word = input()
test_word = test_word.replace("c=", "a")
test_word = test_word.replace("c-", "a")
test_word = test_word.replace("dz=", "a")
test_word = test_word.replace("d-", "a")
test_word = test_word.replace("lj", "a")
test_word = test_word.replace("nj", "a")
test_word = test_word.replace("s=", "a")
test_word = test_word.replace("z=", "a")
print(len(test_word))
